name: Backend CI

on:
  push:
    branches:
      - DEV
      - UAT
      - main
    paths:
      - "backend/**"

  pull_request:
    branches:
      - DEV
      - UAT
      - main
    paths:
      - "backend/**"

jobs:
  backend-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        working-directory: backend
        run: npm ci
